#!/bin/sh

# generates wordpress.conf by combining wordpress.conf-header
# with the URLs in wordprss-urls

outfile=wordpress.conf

echo "## generated by $0 ##" > $outfile
cat wordpress.conf-header >> $outfile

for url in $(egrep -v '^#' wordpress-urls | sed 's/index\.php/(index.php)?/; s/\.php/\\.php/')
do
	cat << EOF >> $outfile
location ~ ${url}$ {
	include snippets/wordpress-nginx/admin-whitelist-ips.conf;
	include snippets/wordpress-nginx/php.conf;
}
EOF
done
