#!/bin/sh

outfile=wordpress.conf

function build_location {
	url=$1
	cat << EOF >> $outfile
location ~ ${url}$ {
	include snippets/wordpress-nginx/admin-whitelist-ips.conf;
	include snippets/wordpress-nginx/php.conf;
}
EOF
}

echo "## generated by $0 ##" > $outfile
cat wordpress.conf-header >> $outfile

for i in $(egrep -v '^#' wordpress-urls | sed 's/index\.php/(index.php)/; s/\.php/\\.php/')
do
    build_location $i
done
